const data = [
  {
    name: "Cotton T-shirt",
    price: 20.99,
    material: "Cotton",
    brand: "Brand A",
  },
  {
    name: "Jeans",
    price: 49.99,
    material: "Denim",
    brand: "Brand B",
  },
  {
    name: "Formal Shirt",
    price: 39.99,
    material: "Polyester",
    brand: "Brand C",
  },
  {
    name: "Summer Dress",
    price: 29.99,
    material: "Chiffon",
    brand: "Brand D",
  },
  {
    name: "Leather Jacket",
    price: 99.99,
    material: "Leather",
    brand: "Brand E",
  },
  {
    name: "Sweatshirt",
    price: 34.99,
    material: "Cotton",
    brand: "Brand F",
  },
  {
    name: "Skirt",
    price: 25.99,
    material: "Cotton Blend",
    brand: "Brand G",
  },
  {
    name: "Hoodie",
    price: 44.99,
    material: "Fleece",
    brand: "Brand H",
  },
  {
    name: "Blazer",
    price: 59.99,
    material: "Wool Blend",
    brand: "Brand I",
  },
  {
    name: "Polo Shirt",
    price: 29.99,
    material: "Cotton",
    brand: "Brand J",
  },
  {
    name: "Maxi Dress",
    price: 39.99,
    material: "Polyester",
    brand: "Brand K",
  },
  {
    name: "Chinos",
    price: 35.99,
    material: "Cotton",
    brand: "Brand L",
  },
  {
    name: "Sweater",
    price: 49.99,
    material: "Wool",
    brand: "Brand M",
  },
  {
    name: "Shorts",
    price: 19.99,
    material: "Cotton",
    brand: "Brand N",
  },
  {
    name: "Jumpsuit",
    price: 59.99,
    material: "Rayon",
    brand: "Brand O",
  },
  {
    name: "Cardigan",
    price: 34.99,
    material: "Acrylic",
    brand: "Brand P",
  },
  {
    name: "Sweatpants",
    price: 29.99,
    material: "Polyester",
    brand: "Brand Q",
  },
  {
    name: "Flannel Shirt",
    price: 45.99,
    material: "Flannel",
    brand: "Brand R",
  },
  {
    name: "Dress Pants",
    price: 54.99,
    material: "Polyester Blend",
    brand: "Brand S",
  },
  {
    name: "Tank Top",
    price: 14.99,
    material: "Cotton",
    brand: "Brand T",
  },
  {
    name: "Trench Coat",
    price: 79.99,
    material: "Cotton Blend",
    brand: "Brand U",
  },
  {
    name: "Cargo Pants",
    price: 39.99,
    material: "Cotton",
    brand: "Brand V",
  },
  {
    name: "Halter Dress",
    price: 49.99,
    material: "Polyester",
    brand: "Brand W",
  },
  {
    name: "Suede Jacket",
    price: 89.99,
    material: "Suede",
    brand: "Brand X",
  },
  {
    name: "Peacoat",
    price: 69.99,
    material: "Wool Blend",
    brand: "Brand Y",
  },
  {
    name: "Pullover",
    price: 39.99,
    material: "Cotton",
    brand: "Brand Z",
  },
];

export default data;
